.\" Manpage for mod-lxqt.
.TH man 1 "8 Mar 2018" "0.1" "mod-lxqt man page"
.SH NAME
mod-lxqt \- lxqt setting
.SH SYNOPSIS
mod-lxqt [command] [options]
.SH DESCRIPTION
mod-lxqt is simple setting for lxqt.
.SH OPTIONS
The mod-lxqt does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-lxqt (play-lxqt@develop)
