.\" Manpage for mod-xfce.
.TH man 1 "8 Mar 2018" "0.1" "mod-xfce man page"
.SH NAME
mod-xfce \- xfce setting
.SH SYNOPSIS
mod-xfce [command] [options]
.SH DESCRIPTION
mod-xfce is simple setting for xfce.
.SH OPTIONS
The mod-xfce does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-xfce (play-xfce@develop)
