.\" Manpage for mod-gnome.
.TH man 1 "8 Mar 2018" "0.1" "mod-gnome man page"
.SH NAME
mod-gnome \- gnome setting
.SH SYNOPSIS
mod-gnome [command] [options]
.SH DESCRIPTION
mod-gnome is simple setting for gnome.
.SH OPTIONS
The mod-gnome does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-gnome (play-gnome@develop)
