#!/usr/bin/env bash


################################################################################
## Head: Manual
##

# $ man bspc
# $ man bspwm
# http://manpages.ubuntu.com/manpages/bionic/en/man1/bspwm.1.html

##
## Tail: Manual
################################################################################


################################################################################
## Head: Examples
##

# $ dpkg -L bspwm | grep bspwmrc
# /usr/share/doc/bspwm/examples/bspwmrc
# /usr/share/doc/bspwm/examples/external_rules/bspwmrc
# /usr/share/doc/bspwm/examples/loop/bspwmrc
# /usr/share/doc/bspwm/examples/overlapping_borders/bspwmrc
# /usr/share/doc/bspwm/examples/panel/bspwmrc


# $ less /usr/share/doc/bspwm/examples/bspwmrc

##
## Tail: Examples
################################################################################


################################################################################
## Head: Keybind
##

sxhkd -c "$HOME/.config/bspwm/sxhkdrc" &

##
## Tail: Keybind
################################################################################


################################################################################
## Head: Set Cursor
##

xsetroot -cursor_name left_ptr

##
## Tail: Set Cursor
################################################################################


################################################################################
### Head: Xresources
##


#test -f "$HOME/.Xresources" && xrdb -load "$HOME/.Xresources"
#test -f "$HOME/.Xresources" && xrdb -merge "$HOME/.Xresources"
#/usr/local/bin/xresources-load.sh

xresources-load.sh


##
### Tail: Xresources
################################################################################


################################################################################
## Head: Style
##

# display style config
bspc config border_width          4
bspc config window_gap            8

#bspc config top_padding           4
#bspc config bottom_padding        4
#bspc config left_padding          4
#bspc config right_padding         4

bspc config split_ratio           0.5

bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config single_monocle        false
bspc config focus_follows_pointer false

bspc config normal_border_color   "#282828"
bspc config active_border_color   "#a89984"
bspc config focused_border_color  "#a89984"
bspc config presel_feedback_color "#98971a"


##
## Tail: Style
################################################################################


################################################################################
## Head: Workspace
##

#bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d 1 2 3 4
bspc monitor -d Term Edit Web File Misc

##
## Tail: Workspace
################################################################################


################################################################################
## Head: Wallpaper
##

#feh --bg-scale "/usr/share/backgrounds/Spices_in_Athens_by_Makis_Chourdakis.jpg" &

## move to ~/bin/wallpaper.sh
wallpaper.sh &

##
## Tail: Wallpaper
################################################################################


################################################################################
## Head: Compton
##

## compton
#compton &
#compton --config ~/.config/compton/compton.conf &
compton --config "$HOME/.config/bspwm/compton/compton.conf" &

##
## Tail: Compton
################################################################################


################################################################################
### Head: Network
##

## network manager applet
#sleep 1 &&
nm-applet &
## Note: refer /etc/xdg/autostart/nm-applet.desktop


## blueman-applet (Package: blueman)
#blueman-applet
## Note: refer /etc/xdg/autostart/blueman.desktop


##
### Tail: Network
################################################################################


################################################################################
### Head: Volume
##


## volumeicon (Package: volumeicon-alsa)
#volumeicon &


## mate-volume-control-status-icon (Package: mate-media)
mate-volume-control-status-icon &

##
### Tail: Volume
################################################################################


################################################################################
### Head: Panel
##

## stalonetray
#stalonetray &

## Panel

## tint2
#tint2 &
#tint2 -c "$HOME/.config/tint2/tint2rc" &
tint2 -c "$HOME/.config/bspwm/tint2/tint2rc" &

## xfce4-panel
#xfce4-panel &

## fbpanel
#fbpanel &

## lxpanel
#lxpanel &

## lxqt-panel
#lxqt-panel &

## cairo-dock
#cairo-dock &

##
### Tail: Panel
################################################################################


################################################################################
### Head: Policykit Agent
##

## [policykit-1-gnome]
## $ dpkg -L policykit-1-gnome | grep desktop
## /etc/xdg/autostart/polkit-gnome-authentication-agent-1.desktop
## $ grep '^Exec=' $(dpkg -L policykit-1-gnome | grep desktop)
## Exec=/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1
## $ grep '^Exec=' $(dpkg -L policykit-1-gnome | grep desktop) | cut -d '=' -f 2
## /usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1

/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &


## [lxqt-policykit]
## $ dpkg -L lxqt-policykit | grep desktop
## /etc/xdg/autostart/lxqt-policykit-agent.desktop
## $ grep '^Exec=' $(dpkg -L lxqt-policykit | grep desktop)
## Exec=lxqt-policykit-agent
## $ grep '^Exec=' $(dpkg -L lxqt-policykit | grep desktop) | cut -d '=' -f 2
## lxqt-policykit-agent

#lxqt-policykit-agent &


## How to test:
## Way 1:
## Use [galternatives](https://manpages.ubuntu.com/manpages/bionic/en/man1/galternatives.1.html).
## Package: [galternatives](https://packages.ubuntu.com/bionic/galternatives)
## Way 2:
## $ pkexec ls

##
### Tail: Policykit Agent
################################################################################


################################################################################
### Head: Screen Saver
##


## xscreensaver
## /etc/xdg/autostart/xscreensaver.desktop
/usr/share/xscreensaver/xscreensaver-wrapper.sh -no-splash &


##
### Tail: Screen Saver
################################################################################


################################################################################
### Head: Rule
##

## /usr/share/doc/bspwm/examples/bspwmrc

bspc rule -a Sakura desktop='^1' follow=on
bspc rule -a Xfce4-terminal desktop='^1' follow=on
bspc rule -a Gnome-terminal desktop='^1' follow=on

bspc rule -a Atom desktop='^2' follow=on
bspc rule -a Mousepad desktop='^2' follow=on
bspc rule -a Gedit desktop='^2' follow=on

bspc rule -a Firefox desktop='^3' follow=on
bspc rule -a Chromium-browser desktop='^3' follow=on
bspc rule -a Google-chrome='^3' follow=on

bspc rule -a pcmanfm-qt desktop='^4' follow=on
bspc rule -a Thunar desktop='^4' follow=on
bspc rule -a Nautilus desktop='^4' follow=on
bspc rule -a Pcmanfm desktop='^4' follow=on
bspc rule -a Spacefm desktop='^4' follow=on


#bspc rule -a Gimp-2.8 desktop='^5' state=floating follow=on
bspc rule -a Gimp-2.8 desktop='^5' follow=on
bspc rule -a Soffice desktop='^5' follow=on
bspc rule -a Audacious desktop='^5' follow=on
bspc rule -a mpv desktop='^5' follow=on
bspc rule -a vlc desktop='^5' follow=on
bspc rule -a smplayer desktop='^5' follow=on



##
### Tail: Rule
################################################################################
