#!/usr/bin/env bash


################################################################################
## Head: Examples
##

# $ dpkg -L bspwm | grep bspwmrc
# /usr/share/doc/bspwm/examples/bspwmrc
# /usr/share/doc/bspwm/examples/external_rules/bspwmrc
# /usr/share/doc/bspwm/examples/loop/bspwmrc
# /usr/share/doc/bspwm/examples/overlapping_borders/bspwmrc
# /usr/share/doc/bspwm/examples/panel/bspwmrc


# $ less /usr/share/doc/bspwm/examples/bspwmrc

##
## Tail: Examples
################################################################################


################################################################################
## Head: Keybind
##

sxhkd -c "$HOME/.config/bspwm/sxhkd/sxhkdrc" &

##
## Tail: Keybind
################################################################################


################################################################################
## Head: Style
##

# display style config
bspc config border_width                1
bspc config window_gap                  8
bspc config top_padding                 4
bspc config bottom_padding              4
bspc config left_padding                4
bspc config right_padding               4
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config gapless_monocle             true
bspc config focus_follows_pointer       true

##
## Tail: Style
################################################################################


################################################################################
## Head: Workspace
##

#bspc monitor VGA-1 -d I II III IV V VI VII VIII IX X
#bspc monitor -d I II III IV V VI VII VIII IX X
#bspc monitor VGA-1 -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor -d 1 2 3 4 5 6 7 8 9 0
bspc monitor -d 1 2 3 4

##
## Tail: Workspace
################################################################################


################################################################################
## Head: Wallpaper
##

feh --bg-scale "/usr/share/backgrounds/Spices_in_Athens_by_Makis_Chourdakis.jpg" &

##
## Tail: Wallpaper
################################################################################


################################################################################
## Head: Compton
##

## compton
#compton &
#compton --config ~/.config/compton/compton.conf &
compton --config "$HOME/.config/bspwm/compton/compton.conf" &

##
## Tail: Compton
################################################################################


################################################################################
### Head: Network
##

## network manager applet
#sleep 1 &&
nm-applet &

##
### Tail: Network
################################################################################


################################################################################
### Head: Mixer
##

## sound mixer
volumeicon &

##
### Tail: Mixer
################################################################################


################################################################################
### Head: Panel
##

## stalonetray
#stalonetray &

## Panel

## tint2
#tint2 &
#tint2 -c "$HOME/.config/tint2/tint2rc" &
tint2 -c "$HOME/.config/bspwm/tint2/tint2rc" &

## xfce4-panel
#xfce4-panel &

## fbpanel
#fbpanel &

## lxpanel
#lxpanel &

## lxqt-panel
#lxqt-panel &

## cairo-dock
#cairo-dock &

##
### Tail: Panel
################################################################################
