.\" Manpage for mod-im.
.TH man 1 "8 Mar 2018" "0.1" "mod-im man page"
.SH NAME
mod-im \- im setting
.SH SYNOPSIS
mod-im [command] [options]
.SH DESCRIPTION
mod-im is simple setting for im.
.SH OPTIONS
The mod-im does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-im (play-im@develop)
