#!/usr/bin/env bash


################################################################################
### Head: Url
##

# * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl
# * https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/

##
### Tail: Url
################################################################################


################################################################################
### Head: Note
##

# $ xfconf-query -c 'xsettings' -l | grep Theme
#
# /Gtk/CursorThemeName
# /Gtk/CursorThemeSize
# /Gtk/KeyThemeName
# /Net/FallbackIconTheme
# /Net/IconThemeName
# /Net/SoundThemeName
# /Net/ThemeName


##
### Tail: Note
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
THE_CMD_FILE_NAME=$(basename $0)
##
### Tail: Init
################################################################################


################################################################################
### Head: Util_Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2;
	fi
}

##
### Head: Util_Debug
################################################################################


################################################################################
### Head: Base
##
find_dir_path () {
	if [ ! -d $(dirname -- "$1") ]; then
		dirname -- "$1"
		return 1
	fi
	echo $(cd -P -- "$(dirname -- "$1")" && pwd -P)
}

##THIS_BASE_DIR_PATH=$(find_dir_path $0)

## $ export DEBUG_SC_CTRL=true
is_debug () {
	if [ "$DEBUG_SC_CTRL" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/../.")
	THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/.")


	THE_CMD_VERSION='0.1'

	THE_CMD_DIR_PATH="${THE_BASE_DIR_PATH}"

	if [ "none${THE_CMD_FILE_NAME}" = 'none' ]; then
		THE_CMD_FILE_NAME="style-ctrl-xfce"
	fi

	THE_CMD_FILE_PATH="${THE_CMD_DIR_PATH}/$THE_CMD_FILE_NAME"

	## https://github.com/samwhelp/play-ubuntu-18.04-plan/blob/master/project/style-tool/xfce/style-ctrl/style-ctrl-xfce
	THE_SELF_UPDATE_URL='https://raw.githubusercontent.com/samwhelp/play-ubuntu-18.04-plan/master/project/style-tool/xfce/style-ctrl/style-ctrl-xfce'


	THE_TMP_DIR_PATH="/tmp"


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"


	THE_PROFILE_DIR_NAME=".${THE_CMD_FILE_NAME}-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="$THE_CMD_FILE_NAME"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="$THE_CMD_FILE_NAME"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="$THE_CMD_FILE_NAME"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"


}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"

	util_debug_echo "THE_CMD_FILE_NAME=$THE_CMD_FILE_NAME"
	util_debug_echo "THE_CMD_FILE_PATH=$THE_CMD_FILE_PATH"
	util_debug_echo "THE_CMD_DIR_PATH=$THE_CMD_DIR_PATH"

	util_debug_echo "THE_SELF_UPDATE_URL=$THE_SELF_UPDATE_URL"


	util_debug_echo "THE_TMP_DIR_PATH=$THE_TMP_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"



	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util_SubCmd
##

sub_cmd_find_function_name () {
	echo "sub_run_$1"
}

##
### Tail: Util_SubCmd
################################################################################


################################################################################
### Head: Util_Self_Update
##

util_make_bin_dir () {
	mkdir -p "$HOME/bin"
}

util_make_tmp_dir () {
	THE_TMP_DIR_PATH="/tmp/tmp.$$.$RANDOM"
	mkdir "$THE_TMP_DIR_PATH"
}

util_self_update_download_to_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	wget -c "$THE_SELF_UPDATE_URL" -O "$tmp_file_path"

}

util_self_update_install_from_tmp_dir () {

	local tmp_file_path="${THE_TMP_DIR_PATH}/${THE_CMD_FILE_NAME}"

	echo "install -m 755 $tmp_file_path $THE_CMD_FILE_PATH"
	install -m 755 "$tmp_file_path" "$THE_CMD_FILE_PATH"

}

util_self_update_check_cmd_exists () {

	if ! [ -f "$THE_CMD_FILE_PATH" ]; then ## file not exists
		return 0
	fi


	echo "File is exists:" "$THE_CMD_FILE_PATH"
	echo

	echo "Try to backup:"
	echo

	local now=$(date +%Y%m%d_%s)
	local bak_dir_path="${THE_CMD_FILE_PATH}.bak"
	local bak_file_path="${bak_dir_path}/${THE_CMD_FILE_NAME}.bak.$now"

	mkdir -p $bak_dir_path

	mv -v "$THE_CMD_FILE_PATH" "${bak_file_path}"

	if [ "$?" != "0" ]; then
		echo
		echo 'Backup Failure!'
		exit 1
	fi

	echo

	return 0
}

util_self_update_print_version () {
	echo
	echo "Current Version:"

	"$THE_CMD_FILE_PATH" version
}

util_self_update () {

	util_make_bin_dir

	util_make_tmp_dir

	util_self_update_download_to_tmp_dir

	util_self_update_check_cmd_exists && util_self_update_install_from_tmp_dir


	util_self_update_print_version

}


main_version () {
	echo $THE_CMD_VERSION
}

util_self_actions () {
	grep '^sub_run' "${THE_CMD_FILE_PATH}" | cut -d ' ' -f 1 | awk -F 'sub_run_' '{print $2}' | sort -u
}

##
### Tail: Util_Self_Update
################################################################################


################################################################################
### Head: Sys
##

sys_xfce_set_wm_theme () {

	local wm_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
	## <property name="theme" type="string" value="Numix"/>

	xfconf-query -c 'xfwm4' -p '/general/theme' -s "$wm_theme"
	echo "xfconf-query -c 'xfwm4' -p '/general/theme' -s '$wm_theme'"

}

sys_xfce_get_wm_theme () {

	xfconf-query -c 'xfwm4' -p '/general/theme'

}

sys_xfce_set_ui_theme () {

	local ui_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="ThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s "$ui_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s '$ui_theme'"

}

sys_xfce_get_ui_theme () {

	xfconf-query -c 'xsettings' -p '/Net/ThemeName'

}

sys_xfce_set_icon_theme () {

	local icon_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="IconThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s "$icon_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s '$icon_theme'"

}

sys_xfce_get_icon_theme () {

	xfconf-query -c 'xsettings' -p '/Net/IconThemeName'

}

sys_xfce_set_cursor_theme () {

	local cursor_theme_name="$1"
	local cursor_theme_size="$2"

	if [ "none${cursor_theme_name}" = "none" ]; then
		cursor_theme_name="default"
	fi

	if [ "none${cursor_theme_size}" = "none" ]; then
		cursor_theme_size="24"
	fi

	#echo $cursor_theme_name
	#echo $cursor_theme_size
	#return


	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

	## <property name="CursorThemeName" type="string" value="default"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="breeze_cursors"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="Breeze_Snow"/>
	## <property name="CursorThemeSize" type="int" value="24"/>


	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s '$cursor_theme_name'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s "$cursor_theme_name"

	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s '$cursor_theme_size'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s "$cursor_theme_size"


}

sys_xfce_get_cursor_theme () {
	local name=$(xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName')

	local size=$(xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize')

	echo "${name} ${size}"
}

sys_xfce_get_all () {

	local wm_theme=$(sys_xfce_get_wm_theme)
	local ui_theme=$(sys_xfce_get_ui_theme)
	local icon_theme=$(sys_xfce_get_icon_theme)
	local cursor_theme=$(sys_xfce_get_cursor_theme)

	echo "wm_theme: ${wm_theme}"
	echo "ui_theme: ${ui_theme}"
	echo "icon_theme: ${icon_theme}"
	echo "cursor_theme: ${cursor_theme}"

}


sys_xfce_get_all_default () {

	local wm_theme=$(sys_xfce_get_wm_theme_default)
	local ui_theme=$(sys_xfce_get_ui_theme_default)
	local icon_theme=$(sys_xfce_get_icon_theme_default)
	local cursor_theme=$(sys_xfce_get_cursor_theme_default)
	local cursor_theme_for_dark=$(sys_xfce_get_cursor_theme_default_for_dark)
	local cursor_theme_for_light=$(sys_xfce_get_cursor_theme_default_for_light)

	echo "wm_theme: ${wm_theme}"
	echo "ui_theme: ${ui_theme}"
	echo "icon_theme: ${icon_theme}"
	echo "cursor_theme: ${cursor_theme}"
	echo "cursor_theme_for_dark: ${cursor_theme_for_dark}"
	echo "cursor_theme_for_light: ${cursor_theme_for_light}"

}

sys_xfce_set_all_default () {

	sys_xfce_set_wm_theme_default
	sys_xfce_set_ui_theme_default
	sys_xfce_set_icon_theme_default
	sys_xfce_set_cursor_theme_default

}

sys_xfce_get_wm_theme_default () {

	echo 'Breeze'

}

sys_xfce_set_wm_theme_default () {

	sys_xfce_set_wm_theme $(sys_xfce_get_wm_theme_default)

}

sys_xfce_get_ui_theme_default () {

	echo 'NumixBlue'

}

sys_xfce_set_ui_theme_default () {

	sys_xfce_set_ui_theme $(sys_xfce_get_ui_theme_default)

}

sys_xfce_get_icon_theme_default () {

	echo 'Numix'

}

sys_xfce_set_icon_theme_default () {

	sys_xfce_set_icon_theme $(sys_xfce_get_icon_theme_default)

}

sys_xfce_get_cursor_theme_default () {

	echo 'breeze_cursors' 24

}

sys_xfce_set_cursor_theme_default () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default)

}

sys_xfce_get_cursor_theme_default_for_dark () {

	echo 'Breeze_Snow' 24

}

sys_xfce_set_cursor_theme_default_for_dark () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default_for_dark)
}

sys_xfce_get_cursor_theme_default_for_light () {

	echo 'breeze_cursors' 24

}

sys_xfce_set_cursor_theme_default_for_light () {

	sys_xfce_set_cursor_theme $(sys_xfce_get_cursor_theme_default_for_light)

}

##
### Tail: Sys
################################################################################



################################################################################
### Head: Model
##

sc_wm_theme_usage () {

	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF

Usage:
	$ $cmd_name wm_theme {name}


Example:
	$ $cmd_name wm_theme 'Breeze'
	$ $cmd_name wm_theme 'Numix'
	$ $cmd_name wm_theme 'NumixBlue'

EOF

}

# sc_wm_theme () {
#
# 	local wm_theme="$1"
#
# 	if [ "none${wm_theme}" = "none" ]; then
# 		echo
# 		echo "## Need {name}"
# 		sc_wm_theme_usage
# 		return
# 	fi
#
# 	sys_xfce_set_wm_theme "$wm_theme"
#
# }

sc_wm_theme () {

	local wm_theme="$1"

	if [ "none${wm_theme}" = "none" ]; then
		sys_xfce_get_wm_theme
		return
	fi

	sys_xfce_set_wm_theme "$wm_theme"

}


sc_ui_theme_usage () {

	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF

Usage:
	$ $cmd_name ui_theme {name}


Example:
	$ $cmd_name ui_theme 'NumixBlue'
	$ $cmd_name ui_theme 'Numix'
	$ $cmd_name ui_theme 'Obsidian-2-Gray'


EOF

}

# sc_ui_theme () {
#
# 	local ui_theme="$1"
#
# 	if [ "none${ui_theme}" = "none" ]; then
# 		echo
# 		echo "## Need {name}"
# 		sc_ui_theme_usage
# 		return
# 	fi
#
# 	sys_xfce_set_ui_theme "$ui_theme"
#
# }

sc_ui_theme () {

	local ui_theme="$1"

	if [ "none${ui_theme}" = "none" ]; then
		sys_xfce_get_ui_theme
		return
	fi

	sys_xfce_set_ui_theme "$ui_theme"

}


sc_icon_theme_usage () {

	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF

Usage:
	$ $cmd_name icon_theme {name}


Example:
	$ $cmd_name icon_theme 'Numix'
	$ $cmd_name icon_theme 'Nord-Black-Frost-Suru'


EOF

}

# sc_icon_theme () {
#
# 	local icon_theme="$1"
#
# 	if [ "none${icon_theme}" = "none" ]; then
# 		echo
# 		echo "## Need {name}"
# 		sc_icon_theme_usage
# 		return
# 	fi
#
# 	sys_xfce_set_icon_theme "$icon_theme"
#
# }

sc_icon_theme () {

	local icon_theme="$1"

	if [ "none${icon_theme}" = "none" ]; then
		sys_xfce_get_icon_theme
		return
	fi

	sys_xfce_set_icon_theme "$icon_theme"

}


sc_cursor_theme_usage () {

	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF

Usage:
	$ $cmd_name cursor_theme {name} [size]


Example:
	$ $cmd_name cursor_theme 'default'

	$ $cmd_name cursor_theme 'breeze_cursors'
	$ $cmd_name cursor_theme 'breeze_cursors' 24

	$ $cmd_name cursor_theme 'Breeze_Snow'

	$ $cmd_name cursor_theme 'DMZ-Black'
	$ $cmd_name cursor_theme 'DMZ-White'

EOF

}

# sc_cursor_theme () {
#
# 	local cursor_theme_name="$1"
# 	local cursor_theme_size="$2"
#
# 	if [ "none${cursor_theme_name}" = "none" ]; then
# 		echo
# 		echo "## Need {name}"
# 		sc_cursor_theme_usage
# 		return
# 	fi
#
# 	sys_xfce_set_cursor_theme "$cursor_theme_name" "$cursor_theme_size"
#
# }

sc_cursor_theme () {

	local cursor_theme_name="$1"
	local cursor_theme_size="$2"

	if [ "none${cursor_theme_name}" = "none" ]; then
		sys_xfce_get_cursor_theme
		return
	fi

	sys_xfce_set_cursor_theme "$cursor_theme_name" "$cursor_theme_size"

}

##
### Tail: Model
################################################################################


################################################################################
### Head: SubCmd
##



sub_run_help () {
	main_usage $@
}

sub_run_version () {
	main_version $@
}

sub_run_self_update () {
	util_self_update $@
}


sub_run_self_actions () {
	util_self_actions $@
}


sub_run_wm_theme () {
	#echo "sub_run_wm_theme"
	sc_wm_theme $@
}

sub_run_wm_theme_help () {
	#echo "sub_run_wm_theme_help"
	sc_wm_theme_usage $@
}

sub_run_ui_theme () {
	#echo "sub_run_ui_theme"
	sc_ui_theme $@
}

sub_run_ui_theme_help () {
	#echo "sub_run_ui_theme_help"
	sc_ui_theme_usage $@
}

sub_run_icon_theme () {
	#echo "sub_run_icon_theme"
	sc_icon_theme $@
}

sub_run_icon_theme_help () {
	#echo "sub_run_icon_theme_help"
	sc_icon_theme_usage $@
}

sub_run_cursor_theme () {
	#echo "sub_run_cursor_theme"
	sc_cursor_theme $@
}

sub_run_cursor_theme_help () {
	#echo "sub_run_cursor_theme_help"
	sc_cursor_theme_usage $@
}



sub_run_all () {
	#echo "sub_run_all"
	#sc_all $@
	sys_xfce_get_all
}

sub_run_all_get_default () {
	#echo "sub_run_all_get_default"
	#sc_get_all_default $@
	sys_xfce_get_all_default
}

sub_run_all_set_default () {
	#echo "sub_run_all_set_default"
	#sc_all_set_default $@
	sys_xfce_set_all_default
}

sub_run_wm_theme_default () {
	#echo "sub_run_wm_theme_default"
	#sc_wm_theme_default $@
	sys_xfce_set_wm_theme_default
}

sub_run_ui_theme_default () {
	#echo "sub_run_ui_theme_default"
	#sc_ui_theme_default $@
	sys_xfce_set_ui_theme_default
}

sub_run_icon_theme_default () {
	#echo "sub_run_icon_theme"
	#sc_icon_theme_default $@
	sys_xfce_set_icon_theme_default
}

sub_run_cursor_theme_default () {
	#echo "sub_run_cursor_theme_default"
	#sc_cursor_theme_default $@
	sys_xfce_set_cursor_theme_default
}


##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="$THE_CMD_FILE_NAME"

cat << EOF
Usage:
	$ $cmd_name [action]

	## version

	$ $cmd_name version

	## self_update

	$ $cmd_name self_update

	## help

	$ $cmd_name wm_theme_help
	$ $cmd_name ui_theme_help
	$ $cmd_name icon_theme_help
	$ $cmd_name cursor_theme_help

	## get or set

	$ $cmd_name wm_theme [name]
	$ $cmd_name ui_theme [name]
	$ $cmd_name icon_theme [name]
	$ $cmd_name cursor_theme [name] [size]

	## get current

	$ $cmd_name all

	## get all default or set all default

	$ $cmd_name all_get_default
	$ $cmd_name all_set_default

	## set default

	$ $cmd_name wm_theme_default
	$ $cmd_name ui_theme_default
	$ $cmd_name icon_theme_default
	$ $cmd_name cursor_theme_default

Example:

	## help

	$ $cmd_name
	$ $cmd_name help

	$ $cmd_name wm_theme_help
	$ $cmd_name ui_theme_help
	$ $cmd_name icon_theme_help
	$ $cmd_name cursor_theme_help

	## get

	$ $cmd_name wm_theme
	$ $cmd_name ui_theme
	$ $cmd_name icon_theme
	$ $cmd_name cursor_theme

	## set

	$ $cmd_name wm_theme 'Breeze'
	$ $cmd_name ui_theme 'NumixBlue'
	$ $cmd_name icon_theme 'Numix'

	$ $cmd_name cursor_theme 'breeze_cursors'
	$ $cmd_name cursor_theme 'breeze_cursors' 24



Debug:
	$ export DEBUG_SC_CTRL=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local args="$@"

	local function_name=$(sub_cmd_find_function_name "$sub_cmd")

	## if ! command -v $function_name > /dev/null; then
	if ! type -p $function_name; then
		util_debug_echo "[Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"

		echo
		main_run_default_sub_cmd "$args"
		return 1
	fi

	"$function_name" "$args" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
