.\" Manpage for mod-tool.
.TH man 1 "8 Mar 2018" "0.1" "mod-tool man page"
.SH NAME
mod-tool \- tool setting
.SH SYNOPSIS
mod-tool [command] [options]
.SH DESCRIPTION
mod-tool is simple setting for tool.
.SH OPTIONS
The mod-tool does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-tool (play-tool@develop)
