#!/usr/bin/env bash


################################################################################
### Head: Url
##

# * https://github.com/samwhelp/skel-project-plan/blob/gh-pages/demo/sh/standalone/bin/demo-ctrl
# * https://www.freedesktop.org/wiki/Specifications/XSettingsRegistry/

##
### Tail: Url
################################################################################


################################################################################
### Head: Init
##
set -e ## for Exit immediately if a command exits with a non-zero status.
THE_BASE_DIR_PATH=$(cd -P -- "$(dirname -- "$0")" && pwd -P)
##
### Tail: Init
################################################################################


################################################################################
### Head: Util_Debug
##

util_debug_echo () {
	if is_debug; then
		echo "$@" 1>&2;
	fi
}

##
### Head: Util_Debug
################################################################################


################################################################################
### Head: Base
##
find_dir_path () {
	if [ ! -d $(dirname -- "$1") ]; then
		dirname -- "$1"
		return 1
	fi
	echo $(cd -P -- "$(dirname -- "$1")" && pwd -P)
}

##THIS_BASE_DIR_PATH=$(find_dir_path $0)

## $ export DEBUG_SS_CTRL=true
is_debug () {
	if [ "$DEBUG_SS_CTRL" = "true" ]; then
		return 0
	fi

	return 1
}

is_not_debug () {
	! is_debug
}

base_var_init () {

	#THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/../.")
	THE_PLAN_DIR_PATH=$(find_dir_path "$THE_BASE_DIR_PATH/.")


	THE_ASSET_DIR_NAME="asset"
	THE_ASSET_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_ASSET_DIR_NAME"

	THE_VAR_DIR_NAME="var"
	THE_VAR_DIR_PATH="$THE_PLAN_DIR_PATH/$THE_VAR_DIR_NAME"


	THE_PROFILE_DIR_NAME=".style-switch-xfce-profile"
	THE_PROFILE_DIR_PATH="$HOME/$THE_PROFILE_DIR_NAME"

	THE_PROJECT_DIR_NAME="style-switch-xfce"
	THE_PROJECT_DIR_PATH="$HOME/.local/share/$THE_PROJECT_DIR_NAME"

	THE_CONFIG_DIR_NAME="style-switch-xfce"
	THE_CONFIG_DIR_PATH="$HOME/.config/$THE_CONFIG_DIR_NAME"

	THE_CACHE_DIR_NAME="style-switch-xfce"
	THE_CACHE_DIR_PATH="$HOME/.cache/$THE_CACHE_DIR_NAME"


}

base_var_dump () {

	is_not_debug && return 0

	util_debug_echo
	util_debug_echo "################################################################################"
	util_debug_echo "### Head: var_dump"
	util_debug_echo "##"
	util_debug_echo "#"


	util_debug_echo "THE_PLAN_DIR_PATH=$THE_PLAN_DIR_PATH"


	util_debug_echo "THE_ASSET_DIR_NAME=$THE_ASSET_DIR_NAME"
	util_debug_echo "THE_ASSET_DIR_PATH=$THE_ASSET_DIR_PATH"

	util_debug_echo "THE_VAR_DIR_NAME=$THE_VAR_DIR_NAME"
	util_debug_echo "THE_VAR_DIR_PATH=$THE_VAR_DIR_PATH"




	util_debug_echo "THE_PROFILE_DIR_NAME=$THE_PROFILE_DIR_NAME"
	util_debug_echo "THE_PROFILE_DIR_PATH=$THE_PROFILE_DIR_PATH"

	util_debug_echo "THE_PROJECT_DIR_NAME=$THE_PROJECT_DIR_NAME"
	util_debug_echo "THE_PROJECT_DIR_PATH=$THE_PROJECT_DIR_PATH"

	util_debug_echo "THE_CONFIG_DIR_NAME=$THE_CONFIG_DIR_NAME"
	util_debug_echo "THE_CONFIG_DIR_PATH=$THE_CONFIG_DIR_PATH"

	util_debug_echo "THE_CACHE_DIR_NAME=$THE_CACHE_DIR_NAME"
	util_debug_echo "THE_CACHE_DIR_PATH=$THE_CACHE_DIR_PATH"



	util_debug_echo "#"
	util_debug_echo "##"
	util_debug_echo "### Tail: var_dump"
	util_debug_echo "################################################################################"
	util_debug_echo
}


base_var_init

base_var_dump

##
### Tail: Base
################################################################################


################################################################################
### Head: Util_SubCmd
##

sub_cmd_find_function_name () {
	echo "sub_run_$1"
}

##
### Tail: Util_SubCmd
################################################################################




################################################################################
### Head: Sys
##

sys_xfce_set_wm_theme () {

	local wm_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
	## <property name="theme" type="string" value="Numix"/>

	xfconf-query -c 'xfwm4' -p '/general/theme' -s "$wm_theme"
	echo "xfconf-query -c 'xfwm4' -p '/general/theme' -s '$wm_theme'"

}

sys_xfce_set_ui_theme () {

	local ui_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="ThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s "$ui_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/ThemeName' -s '$ui_theme'"

}

sys_xfce_set_icon_theme () {

	local icon_theme="$1"

	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
	## <property name="IconThemeName" type="string" value="Numix"/>

	xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s "$icon_theme"
	echo "xfconf-query -c 'xsettings' -p '/Net/IconThemeName' -s '$icon_theme'"

}

sys_xfce_set_cursor_theme () {

	local cursor_theme_name="$1"
	local cursor_theme_size="$2"

	if [ "none${cursor_theme_name}" = "none" ]; then
		cursor_theme_name="default"
	fi

	if [ "none${cursor_theme_size}" = "none" ]; then
		cursor_theme_size="24"
	fi

	#echo $cursor_theme_name
	#echo $cursor_theme_size
	#return


	## ~/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml

	## <property name="CursorThemeName" type="string" value="default"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="breeze_cursors"/>
	## <property name="CursorThemeSize" type="int" value="24"/>

	## <property name="CursorThemeName" type="string" value="Breeze_Snow"/>
	## <property name="CursorThemeSize" type="int" value="24"/>


	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s '$cursor_theme_name'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeName' -s "$cursor_theme_name"

	echo "xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s '$cursor_theme_size'"
	xfconf-query -c 'xsettings' -p '/Gtk/CursorThemeSize' -s "$cursor_theme_size"


}

sys_xfce_set_all_default () {

	sys_xfce_set_wm_theme_default
	sys_xfce_set_ui_theme_default
	sys_xfce_set_icon_theme_default
	sys_xfce_set_cursor_theme_default

}

sys_xfce_set_wm_theme_default () {

	sys_xfce_set_wm_theme 'Breeze'

}

sys_xfce_set_ui_theme_default () {

	sys_xfce_set_ui_theme 'NumixBlue'

}

sys_xfce_set_icon_theme_default () {

	sys_xfce_set_icon_theme 'Numix'

}

sys_xfce_set_cursor_theme_default () {

	sys_xfce_set_cursor_theme 'breeze_cursors' 24

}

sys_xfce_set_cursor_theme_default_for_dark () {

	sys_xfce_set_cursor_theme 'Breeze_Snow' 24

}

sys_xfce_set_cursor_theme_default_for_light () {

	sys_xfce_set_cursor_theme 'breeze_cursors' 24

}

##
### Tail: Sys
################################################################################


################################################################################
### Head: Model ss_numix
##

ss_numix_config_wm_theme () {

	sys_xfce_set_wm_theme 'Numix'

}

ss_numix_config_ui_theme () {

	sys_xfce_set_ui_theme 'Numix'

}

ss_numix_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix'

}

ss_numix_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}


ss_numix () {
	#echo "ss_numix"
	#echo "$@"


	ss_numix_config_wm_theme
	ss_numix_config_ui_theme
	ss_numix_config_icon_theme
	ss_numix_config_cursor_theme

}

##
### Tail: Model ss_numix
################################################################################


################################################################################
### Head: Model ss_numix_blue
##

ss_numix_blue_config_wm_theme () {

	sys_xfce_set_wm_theme 'NumixBlue'

}

ss_numix_blue_config_ui_theme () {

	sys_xfce_set_ui_theme 'NumixBlue'

}

ss_numix_blue_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix'

}

ss_numix_blue__config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ss_numix_blue () {
	#echo "ss_numix_blue"
	#echo "$@"


	ss_numix_blue_config_wm_theme
	ss_numix_blue_config_ui_theme
	ss_numix_blue_config_icon_theme
	ss_numix_blue__config_cursor_theme

}

##
### Tail: Model ss_numix_blue
################################################################################


################################################################################
### Head: Model ss_numix_blue_wm_breeze
##

ss_numix_blue_wm_breeze_config_wm_theme () {

	sys_xfce_set_wm_theme 'Breeze'

}

ss_numix_blue_wm_breeze_config_ui_theme () {

	sys_xfce_set_ui_theme 'NumixBlue'

}

ss_numix_blue_wm_breeze_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix'

}

ss_numix_blue_wm_breeze_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ss_numix_blue_wm_breeze () {
	#echo "ss_numix_blue_wm_breeze"
	#echo "$@"


	ss_numix_blue_wm_breeze_config_wm_theme
	ss_numix_blue_wm_breeze_config_ui_theme
	ss_numix_blue_wm_breeze_config_icon_theme
	ss_numix_blue_wm_breeze_config_cursor_theme

}

##
### Tail: Model ss_numix_blue_wm_breeze
################################################################################


################################################################################
### Head: Model ss_obsidian_2_gray
##

ss_obsidian_2_gray_config_wm_theme () {

	sys_xfce_set_wm_theme 'Obsidian-2-Gray'

}

ss_obsidian_2_gray_config_ui_theme () {

	sys_xfce_set_ui_theme 'Obsidian-2-Gray'


}

ss_obsidian_2_gray_config_icon_theme () {

	sys_xfce_set_icon_theme 'Nord-Black-Frost-Suru'

}

ss_obsidian_2_gray_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ss_obsidian_2_gray () {
	#echo "ss_obsidian_2_gray"
	#echo "$@"


	ss_obsidian_2_gray_config_wm_theme
	ss_obsidian_2_gray_config_ui_theme
	ss_obsidian_2_gray_config_icon_theme
	ss_obsidian_2_gray_config_cursor_theme

}

##
### Tail: Model ss_obsidian_2_gray
################################################################################


################################################################################
### Head: Model ss_fantome_wm_2bxfwm_lucy
##

ss_fantome_wm_2bxfwm_lucy_config_wm_theme () {

	sys_xfce_set_wm_theme '2bxfwm-Lucy'

}

ss_fantome_wm_2bxfwm_lucy_config_ui_theme () {

	sys_xfce_set_ui_theme 'Fantome'

}

ss_fantome_wm_2bxfwm_lucy_config_icon_theme () {

	sys_xfce_set_icon_theme 'Nord-Black-Frost-Suru'

}

ss_fantome_wm_2bxfwm_lucy_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ss_fantome_wm_2bxfwm_lucy () {
	#echo "ss_fantome_wm_2bxfwm_lucy"
	#echo "$@"


	ss_fantome_wm_2bxfwm_lucy_config_wm_theme
	ss_fantome_wm_2bxfwm_lucy_config_ui_theme
	ss_fantome_wm_2bxfwm_lucy_config_icon_theme
	ss_fantome_wm_2bxfwm_lucy_config_cursor_theme

}

##
### Tail: Model ss_fantome_wm_2bxfwm_lucy
################################################################################


################################################################################
### Head: Model ss_honda_super_cub_wm_chandelier
##

ss_honda_super_cub_wm_chandelier_config_wm_theme () {

	sys_xfce_set_wm_theme 'Chandelier'

}

ss_honda_super_cub_wm_chandelier_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

ss_honda_super_cub_wm_chandelier_config_icon_theme () {

	sys_xfce_set_icon_theme 'Numix'

}

ss_honda_super_cub_wm_chandelier_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default_for_dark

}

ss_honda_super_cub_wm_chandelier () {
	#echo "ss_honda_super_cub_wm_chandelier"
	#echo "$@"


	ss_honda_super_cub_wm_chandelier_config_wm_theme
	ss_honda_super_cub_wm_chandelier_config_ui_theme
	ss_honda_super_cub_wm_chandelier_config_icon_theme
	ss_honda_super_cub_wm_chandelier_config_cursor_theme

}

##
### Tail: Model ss_honda_super_cub_wm_chandelier
################################################################################


################################################################################
### Head: Model ss_honda_super_cub_wm_rgapsline
##

ss_honda_super_cub_wm_rgapsline_config_wm_theme () {

	sys_xfce_set_wm_theme 'RGapsLine'

}

ss_honda_super_cub_wm_rgapsline_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

ss_honda_super_cub_wm_rgapsline_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

ss_honda_super_cub_wm_rgapsline_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default_for_dark

}

ss_honda_super_cub_wm_rgapsline () {
	#echo "ss_honda_super_cub_wm_rgapsline"
	#echo "$@"


	ss_honda_super_cub_wm_rgapsline_config_wm_theme
	ss_honda_super_cub_wm_rgapsline_config_ui_theme
	ss_honda_super_cub_wm_rgapsline_config_icon_theme
	ss_honda_super_cub_wm_rgapsline_config_cursor_theme

}

##
### Tail: Model ss_honda_super_cub_wm_rgapsline
################################################################################


################################################################################
### Head: Model ss_honda_super_cub_wm_pastel_dark
##

ss_honda_super_cub_wm_pastel_dark_config_wm_theme () {

	sys_xfce_set_wm_theme 'Pastel_Dark'

}

ss_honda_super_cub_wm_pastel_dark_config_ui_theme () {

	sys_xfce_set_ui_theme 'Honda-Super-Cub'

}

ss_honda_super_cub_wm_pastel_dark_config_icon_theme () {

	sys_xfce_set_icon_theme 'Papirus-Dark'

}

ss_honda_super_cub_wm_pastel_dark_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default

}

ss_honda_super_cub_wm_pastel_dark () {
	#echo "ss_honda_super_cub_wm_pastel_dark"
	#echo "$@"


	ss_honda_super_cub_wm_pastel_dark_config_wm_theme
	ss_honda_super_cub_wm_pastel_dark_config_ui_theme
	ss_honda_super_cub_wm_pastel_dark_config_icon_theme
	ss_honda_super_cub_wm_pastel_dark_config_cursor_theme

}

##
### Tail: Model ss_honda_super_cub_wm_pastel_dark
################################################################################


################################################################################
### Head: Model ss_sephia_wm_honda_super_cub
##

ss_sephia_wm_honda_super_cub_config_wm_theme () {

	sys_xfce_set_wm_theme 'Honda-Super-Cub'

}

ss_sephia_wm_honda_super_cub_config_ui_theme () {

	sys_xfce_set_ui_theme 'Sephia'

}

ss_sephia_wm_honda_super_cub_config_icon_theme () {

	sys_xfce_set_icon_theme 'Nord-Black-Frost-Numix'

}

ss_sephia_wm_honda_super_cub_config_cursor_theme () {

	sys_xfce_set_cursor_theme_default_for_light

}

ss_sephia_wm_honda_super_cub () {
	#echo "ss_sephia_wm_honda_super_cub"
	#echo "$@"


	ss_sephia_wm_honda_super_cub_config_wm_theme
	ss_sephia_wm_honda_super_cub_config_ui_theme
	ss_sephia_wm_honda_super_cub_config_icon_theme
	ss_sephia_wm_honda_super_cub_config_cursor_theme

}

##
### Tail: Model ss_sephia_wm_honda_super_cub
################################################################################


################################################################################
### Head: SubCmd
##

sub_run_help () {
	main_usage $@
}

sub_run_default () {
	#echo "sub_run_numix"
	#ss_default $@
	sys_xfce_set_all_default
}

sub_run_numix () {
	#echo "sub_run_numix"
	ss_numix $@
}

sub_run_numix_blue () {
	#echo "sub_run_numix_blue"
	ss_numix_blue $@
}

sub_run_numix_blue_wm_breeze () {
	#echo "sub_run_numix_blue_wm_breeze"
	ss_numix_blue_wm_breeze $@
}

sub_run_obsidian_2_gray () {
	#echo "sub_run_obsidian_2_gray"
	ss_obsidian_2_gray $@
}

sub_run_fantome_wm_2bxfwm_lucy () {
	#echo "sub_run_fantome_wm_2bxfwm_lucy"
	ss_fantome_wm_2bxfwm_lucy $@
}

sub_run_honda_super_cub_wm_chandelier () {
	#echo "sub_run_honda_super_cub_wm_chandelier"
	ss_honda_super_cub_wm_chandelier $@
}

sub_run_honda_super_cub_wm_rgapsline () {
	#echo "sub_run_honda_super_cub_wm_rgapsline"
	ss_honda_super_cub_wm_rgapsline $@
}

sub_run_honda_super_cub_wm_pastel_dark () {
	#echo "sub_run_honda_super_cub_wm_pastel_dark"
	ss_honda_super_cub_wm_pastel_dark $@
}

sub_run_sephia_wm_honda_super_cub () {
	#echo "sub_run_sephia_wm_honda_super_cub"
	ss_sephia_wm_honda_super_cub $@
}

##
### Tail: SubCmd
################################################################################


################################################################################
### Head: Main
##

main_usage () {
	##local cmd_name="$0"
	local cmd_name="style-switch-xfce"

cat << EOF
Usage:
	$ $cmd_name [action]

Example:

	$ $cmd_name
	$ $cmd_name help

	$ $cmd_name default

	$ $cmd_name numix
	$ $cmd_name numix_blue
	$ $cmd_name numix_blue_wm_breeze

	$ $cmd_name obsidian_2_gray

	$ $cmd_name fantome_wm_2bxfwm_lucy

	$ $cmd_name honda_super_cub_wm_chandelier
	$ $cmd_name honda_super_cub_wm_rgapsline
	$ $cmd_name honda_super_cub_wm_pastel_dark

	$ $cmd_name sephia_wm_honda_super_cub



Debug:
	$ export DEBUG_SS_CTRL=true

EOF

}

main_check_args_size () {
	if [ $1 -le 0 ]; then
		shift
		main_run_default_sub_cmd "$@"
		exit 1
	fi
}

main_run_default_sub_cmd () {
	main_usage "$@"
}

main_run_sub_cmd () {

	local sub_cmd="$1"

	shift

	local args="$@"

	local function_name=$(sub_cmd_find_function_name "$sub_cmd")

	## if ! command -v $function_name > /dev/null; then
	if ! type -p $function_name; then
		util_debug_echo "[Debug] sub_cmd_function_not_exist: sub_cmd=$sub_cmd; function_name=$function_name"

		echo
		main_run_default_sub_cmd "$args"
		return 1
	fi

	"$function_name" "$args" ## run sub cmd function


}

## Start
main_check_args_size $# "$@"

main_run_sub_cmd "$@"

##
### Tail: Main
################################################################################
