default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [command]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make en_us'
	@echo
	@echo '	$$ make zh_tw'
	@echo
.PHONY: help


en_us:
	@./en_us-install.sh
.PHONY: en_us


zh_tw:
	@./zh_tw-install.sh
.PHONY: zh_tw
