.\" Manpage for mod-font.
.TH man 1 "8 Mar 2018" "0.1" "mod-font man page"
.SH NAME
mod-font \- font setting
.SH SYNOPSIS
mod-font [command] [options]
.SH DESCRIPTION
mod-font is simple setting for font.
.SH OPTIONS
The mod-font does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-font (play-font@develop)
