default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [command]'
	@echo
	@echo 'Ex:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make us'
	@echo
	@echo '	$$ make tw'
	@echo
.PHONY: help


us:
	@./us-install.sh
.PHONY: us


tw:
	@./tw-install.sh
.PHONY: tw-install
