.\" Manpage for mod-locale.
.TH man 1 "8 Mar 2018" "0.1" "mod-locale man page"
.SH NAME
mod-locale \- locale setting
.SH SYNOPSIS
mod-locale [command] [options]
.SH DESCRIPTION
mod-locale is simple setting for locale.
.SH OPTIONS
The mod-locale does not take any options.
.SH COMMAND
help

	show help

install

	install all tools and settings.

remove

	remove all tools and reset settings.

pkg-install

	install all tools.

pkg-remove

	remove all tools.

conf-set

	set all settings.

conf-reset

	reset all settings.

.SH SEE ALSO
None
.SH BUGS
Unknown bugs.
.SH AUTHOR
paly-locale (play-locale@develop)
