default: help
.PHONY: default

help:
	@echo 'Usage:'
	@echo '	$$ make [action]'
	@echo
	@echo 'Example:'
	@echo '	$$ make'
	@echo '	$$ make help'
	@echo
	@echo '	$$ make install'
	@echo

.PHONY: help

install:
	install -m 755 bin/bspwm-run.sh ~/bin/bspwm-run.sh
.PHONY: install
